//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standard
    {
        public int Standard_ID { get; set; }
        public string StandardName { get; set; }
        public string Description { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
